"""智能体孵化层：沉淀新智能体蓝图、脚手架与标准化生成流程。"""

from agent_compliance.incubator.blueprints import (
    AgentBlueprint,
    AgentBlueprintTemplate,
    BLUEPRINT_TEMPLATE_REGISTRY,
    BUDGET_ANALYSIS_AGENT_TEMPLATE,
    BUDGET_AGENT_BLUEPRINT,
    COMPARISON_EVAL_AGENT_TEMPLATE,
    DEMAND_RESEARCH_AGENT_TEMPLATE,
    DEMAND_RESEARCH_AGENT_BLUEPRINT,
    REVIEW_AGENT_BLUEPRINT,
    REVIEW_AGENT_TEMPLATE,
    SPECIAL_CHECKS_AGENT_BLUEPRINT,
    budget_agent_blueprint,
    create_agent_blueprint,
    demand_research_agent_blueprint,
    get_blueprint,
    get_blueprint_template,
    list_blueprints,
    list_blueprint_templates,
    review_agent_blueprint,
    special_checks_agent_blueprint,
)
from agent_compliance.incubator.lifecycle import (
    DEFAULT_INCUBATION_LIFECYCLE,
    DistillationRecommendation,
    IncubationEvent,
    IncubationStage,
    IncubationStageDefinition,
    IncubationRun,
    IncubationStageRecord,
    SampleSet,
    ValidationComparison,
    create_incubation_run,
    default_incubation_lifecycle,
)
from agent_compliance.incubator.evals import (
    build_distillation_report,
    build_run_comparison_report,
    render_distillation_report_markdown,
    render_run_comparison_markdown,
)
from agent_compliance.incubator.distillation_engine import (
    build_distillation_recommendations,
    summarize_validation_gaps,
)
from agent_compliance.incubator.comparison_builder import (
    build_validation_comparison,
    build_validation_comparison_from_files,
)
from agent_compliance.incubator.comparison_collector import (
    collect_validation_comparisons_from_manifest,
    collect_validation_comparisons_from_root,
)
from agent_compliance.incubator.regression_runner import (
    RegressionFeedback,
    build_regression_feedback,
)
from agent_compliance.incubator.factory import (
    FactoryBootstrapResult,
    bootstrap_agent_factory,
    resume_agent_factory,
)
from agent_compliance.incubator.sample_registry import (
    SampleAsset,
    SampleManifest,
    build_sample_manifest,
    deserialize_sample_manifest,
    load_sample_manifest,
    serialize_sample_manifest,
    summarize_sample_manifest,
    write_sample_manifest,
)
from agent_compliance.incubator.report_writer import (
    DistillationArtifactPaths,
    write_distillation_report,
)
from agent_compliance.incubator.run_store import (
    IncubationRunPaths,
    load_incubation_run,
    serialize_incubation_run,
    write_incubation_run,
)
from agent_compliance.incubator.productize import (
    ProductizationArtifactPaths,
    build_productization_package,
    render_productization_markdown,
    write_productization_package,
)
from agent_compliance.incubator.requirement_definition import (
    RequirementDefinitionDraft,
    RequirementDefinitionPaths,
    build_requirement_definition,
    render_requirement_definition_markdown,
    write_requirement_definition,
)
from agent_compliance.incubator.scaffold_generator import (
    ScaffoldPlan,
    build_scaffold_plan,
    generate_agent_scaffold,
)
from agent_compliance.incubator.scaffolds import render_scaffold_file

__all__ = [
    "DEFAULT_INCUBATION_LIFECYCLE",
    "AgentBlueprint",
    "AgentBlueprintTemplate",
    "BLUEPRINT_TEMPLATE_REGISTRY",
    "BUDGET_ANALYSIS_AGENT_TEMPLATE",
    "BUDGET_AGENT_BLUEPRINT",
    "COMPARISON_EVAL_AGENT_TEMPLATE",
    "DEMAND_RESEARCH_AGENT_TEMPLATE",
    "DEMAND_RESEARCH_AGENT_BLUEPRINT",
    "DistillationRecommendation",
    "DistillationArtifactPaths",
    "IncubationEvent",
    "FactoryBootstrapResult",
    "IncubationStage",
    "IncubationStageDefinition",
    "IncubationRun",
    "IncubationRunPaths",
    "IncubationStageRecord",
    "ProductizationArtifactPaths",
    "RequirementDefinitionDraft",
    "RequirementDefinitionPaths",
    "RegressionFeedback",
    "REVIEW_AGENT_BLUEPRINT",
    "REVIEW_AGENT_TEMPLATE",
    "SPECIAL_CHECKS_AGENT_BLUEPRINT",
    "SampleSet",
    "ScaffoldPlan",
    "SampleAsset",
    "ValidationComparison",
    "SampleManifest",
    "build_scaffold_plan",
    "build_distillation_report",
    "build_run_comparison_report",
    "build_distillation_recommendations",
    "build_sample_manifest",
    "bootstrap_agent_factory",
    "build_regression_feedback",
    "build_productization_package",
    "build_requirement_definition",
    "build_validation_comparison",
    "build_validation_comparison_from_files",
    "collect_validation_comparisons_from_manifest",
    "collect_validation_comparisons_from_root",
    "budget_agent_blueprint",
    "create_agent_blueprint",
    "deserialize_sample_manifest",
    "demand_research_agent_blueprint",
    "create_incubation_run",
    "default_incubation_lifecycle",
    "generate_agent_scaffold",
    "get_blueprint",
    "get_blueprint_template",
    "list_blueprints",
    "list_blueprint_templates",
    "load_sample_manifest",
    "load_incubation_run",
    "render_distillation_report_markdown",
    "render_productization_markdown",
    "render_requirement_definition_markdown",
    "render_run_comparison_markdown",
    "resume_agent_factory",
    "review_agent_blueprint",
    "special_checks_agent_blueprint",
    "render_scaffold_file",
    "serialize_incubation_run",
    "serialize_sample_manifest",
    "summarize_sample_manifest",
    "summarize_validation_gaps",
    "write_distillation_report",
    "write_incubation_run",
    "write_productization_package",
    "write_requirement_definition",
    "write_sample_manifest",
]
