from __future__ import annotations

import re

from agent_compliance.agents.compliance_review.rules.base import RuleDefinition


RULES = [
    RuleDefinition(
        rule_id="CONTRACT-001",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"财政审批的原因造成采购人延期付款|预付款未支付时，中标人仍必须在交货期内交货"),
        rationale="将付款和履约风险大面积转嫁给供应商，权利义务失衡。",
        severity_score=3,
        related_rule_ids=("RULE-008", "RULE-017", "RULE-003"),
        related_reference_ids=("CASESRC-009", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="补充合理顺延和协商机制，避免当然免责和单方转嫁风险。",
        merge_key="contract-payment-risk-shift",
    ),
    RuleDefinition(
        rule_id="CONTRACT-002",
        issue_type="unclear_acceptance_standard",
        pattern=re.compile(r"第三方质量检测部门|最新标准执行|采购人需要"),
        rationale="验收和第三方检测边界不清，可能引发履约争议。",
        severity_score=2,
        related_rule_ids=("RULE-003", "RULE-016"),
        related_reference_ids=("CASESRC-008", "LEGAL-001"),
        source_section="验收条件",
        rewrite_hint="明确验收清单、触发条件、检测范围和费用规则。",
        merge_key="contract-acceptance-boundary",
    ),
    RuleDefinition(
        rule_id="CONTRACT-003",
        issue_type="template_mismatch",
        pattern=re.compile(r"卫生清洁、保洁|垃圾的分类收集、清运|碳足迹盘查报告"),
        rationale="存在与项目主标的关系不清的义务或模板残留内容。",
        severity_score=2,
        related_rule_ids=("RULE-003",),
        related_reference_ids=("LEGAL-001",),
        source_section="商务要求",
        rewrite_hint="删除与主标的不直接相关的义务，或改成与安装履约直接相关的要求。",
        merge_key="contract-template-residue",
    ),
    RuleDefinition(
        rule_id="CONTRACT-004",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"相关损失及责任均与采购人无关|采购人对此不承担任何责任|一切事故.*全部由供应商承担|负全部安全责任|负全责"),
        rationale="条款采用绝对免责或无限扩大供应商责任的表述，容易造成合同权利义务明显失衡。",
        severity_score=2,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("CASESRC-009", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="按过错和责任来源划分责任，删除“采购人不承担任何责任”“一切事故全部由供应商承担”等绝对化表述。",
        merge_key="contract-liability-imbalance",
    ),
    RuleDefinition(
        rule_id="CONTRACT-005",
        issue_type="payment_acceptance_linkage",
        pattern=re.compile(r"终验款.*抽检终验后|原材料和成品经抽样检测合格后才可进行验收|抽样检测不合格导致的检测费"),
        rationale="将付款、终验与抽检或外部检测流程深度绑定，可能导致回款周期和验收边界不确定。",
        severity_score=2,
        related_rule_ids=("RULE-016", "RULE-017"),
        related_reference_ids=("CASESRC-008", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="明确抽检、终验、付款之间的先后关系和超期处理规则，避免把外部流程风险完全转嫁给供应商。",
        merge_key="contract-payment-acceptance-link",
    ),
    RuleDefinition(
        rule_id="CONTRACT-006",
        issue_type="payment_acceptance_linkage",
        pattern=re.compile(r"待财政资金到位后支付|收到财政资金后支付|财政资金拨付后支付|内部审批完成后支付|验收合格且财政资金到位后支付"),
        rationale="将付款节点与财政拨付或采购人内部流程深度绑定，可能导致回款周期不确定。",
        severity_score=2,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("CASESRC-009", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="明确财政拨付或内部审批未完成时的顺延边界、最长支付期限和协商机制，避免供应商承担不确定回款风险。",
        merge_key="contract-payment-acceptance-link",
    ),
    RuleDefinition(
        rule_id="CONTRACT-007",
        issue_type="unclear_acceptance_standard",
        pattern=re.compile(r"抽检不合格.*复检|复检.*由供应商承担|整改后重新验收|返工后重新验收|重新检测费用由供应商承担"),
        rationale="抽检、复检、整改和重新验收的触发条件及费用边界不清，容易引发履约争议。",
        severity_score=2,
        related_rule_ids=("RULE-016", "RULE-017"),
        related_reference_ids=("CASESRC-008", "LEGAL-001"),
        source_section="验收条件",
        rewrite_hint="补充抽检、复检、整改、复验的触发条件、时限和费用承担边界。",
        merge_key="contract-acceptance-boundary",
    ),
    RuleDefinition(
        rule_id="CONTRACT-008",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"采购人有权单方解除合同|采购人可单方解除合同|单方解除本合同|采购人有权解除合同且无需承担责任"),
        rationale="赋予采购人过宽的单方解除权，且未明确触发条件、整改机会和责任边界，容易造成合同失衡。",
        severity_score=2,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("CASESRC-009", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="明确单方解除的触发条件、整改期限和责任后果，避免赋予采购人过宽解除权。",
        merge_key="contract-termination-imbalance",
    ),
    RuleDefinition(
        rule_id="CONTRACT-009",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"违约金按合同总价.*%|按合同总金额.*支付违约金|扣除全部履约保证金|从应付货款中直接扣除|直接扣减合同价款"),
        rationale="违约金、扣款或保证金处理方式过重且边界不清，容易导致供应商承担明显失衡的违约责任。",
        severity_score=2,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("CASESRC-009", "LEGAL-001"),
        source_section="商务要求",
        rewrite_hint="细化违约金、扣款、保证金处理的触发条件、计算方式和责任边界，避免当然扣减或过度处罚。",
        merge_key="contract-deduction-imbalance",
    ),
    RuleDefinition(
        rule_id="CONTRACT-010",
        issue_type="geographic_restriction",
        pattern=re.compile(r"本地服务团队.*到场|本地驻点服务|项目所在地驻场|在项目所在地设有常驻服务人员|深圳市内.*小时内到场|本地工程师.*响应|驻点服务站|本地售后网点|12小时内提供备件|24小时内到场"),
        rationale="在服务响应、驻场或到场要求中嵌入本地团队、本地驻点或属地人员要求，可能构成变相属地限制。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="商务要求",
        rewrite_hint="删除本地团队、驻点或属地人员要求，改为统一的到场时限、响应时效和服务方案要求。",
        merge_key="contract-geographic-service",
    ),
    RuleDefinition(
        rule_id="CONTRACT-011",
        issue_type="payment_acceptance_linkage",
        pattern=re.compile(r"正常运行三个月后.*支付合同总价|设备正常运行三个月后"),
        rationale="将尾款支付与较长试运行周期绑定，容易导致回款周期不稳定和履约争议。",
        severity_score=2,
        related_rule_ids=("RULE-016", "RULE-017"),
        related_reference_ids=("LEGAL-001", "CASESRC-008"),
        source_section="商务要求",
        rewrite_hint="明确试运行期和尾款支付条件，避免把较长运行周期当然作为付款前提。",
        merge_key="contract-payment-acceptance-link",
    ),
    RuleDefinition(
        rule_id="CONTRACT-012",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"采购人不承担任何责任及相关费用|采购人不承担任何责任"),
        rationale="采购人绝对免责表述过于宽泛，未区分现场条件、配合义务和过错来源，容易造成责任失衡。",
        severity_score=2,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("LEGAL-001", "CASESRC-009"),
        source_section="商务要求",
        rewrite_hint="按责任来源划分运输和现场配合义务，删除采购人绝对免责表述。",
        merge_key="contract-liability-imbalance",
    ),
    RuleDefinition(
        rule_id="CONTRACT-013",
        issue_type="unclear_acceptance_standard",
        pattern=re.compile(r"空气检测费用.*由供应商承担|监理.*费用.*由供应商承担|专家评审.*费用.*由供应商承担|整改费用.*由供应商承担|复验费用.*由供应商承担|送检费用.*由供应商承担|抽检费用.*由供应商承担"),
        rationale="将验收、检测、监理、复验或整改费用笼统要求由供应商承担，容易造成费用边界和责任边界失衡。",
        severity_score=2,
        related_rule_ids=("RULE-016", "RULE-017"),
        related_reference_ids=("CASESRC-008", "LEGAL-001"),
        source_section="验收条件",
        rewrite_hint="区分监理、验收、抽检、复验和整改费用的触发条件与责任边界，不宜一概由供应商承担。",
        merge_key="contract-acceptance-boundary",
    ),
    RuleDefinition(
        rule_id="CONTRACT-014",
        issue_type="one_sided_commercial_term",
        pattern=re.compile(r"履约保证金自动转为售后服务保证金|自动转为质保保证金|质保期满后无息退还|验收后转为售后保证金|售后服务保证金.*质保期结束后退还|履约保证金不予退还直至质保期满"),
        rationale="通过履约保证金转质保金、售后保证金或长周期无息占压安排，容易形成异常资金占用。",
        severity_score=3,
        related_rule_ids=("RULE-008", "RULE-017"),
        related_reference_ids=("LEGAL-001", "CASESRC-009"),
        source_section="商务要求",
        rewrite_hint="单独校准履约保证金和质保责任，不宜以自动转保证金、长周期无息占压的方式持续占用供应商资金。",
        merge_key="contract-payment-risk-shift",
    ),
]
