from __future__ import annotations

import re

from agent_compliance.agents.compliance_review.rules.base import RuleDefinition


RULES = [
    RuleDefinition(
        rule_id="QUAL-001",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"外商投资及民营企业|国资企业不具备投标资格"),
        rationale="按企业性质限制供应商范围，可能构成差别待遇。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业性质限制，改回法定主体资格和履约必需能力要求。",
        merge_key="qualification-entity-type",
    ),
    RuleDefinition(
        rule_id="QUAL-002",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"注册资本不低于|年收入不低于|净利润不低于|经营年限不低于|年平均盈利不低于"),
        rationale="设置与项目履约弱相关的一般性财务或经营年限门槛。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-007", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除一般性财务和经营年限门槛，改用法定资质和履约能力证明。",
        merge_key="qualification-financial-threshold",
    ),
    RuleDefinition(
        rule_id="QUAL-003",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"国家级高新技术企业|AAA"),
        rationale="将企业称号、荣誉或信用等级作为门槛或高权重因素，可能与履约无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-010", "RULE-014"),
        related_reference_ids=("LEGAL-001", "CASESRC-001", "CASESRC-006"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业称号或荣誉门槛，改为与标的直接相关的履约能力条件。",
        merge_key="qualification-award",
    ),
    RuleDefinition(
        rule_id="QUAL-004",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"上级主管单位.*同意其参与投标的函件"),
        rationale="以主管单位同意函作为参与前提，通常与一般货物采购履约能力无直接对应关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除主管单位同意函要求，仅保留法定主体资格和履约所必需的证明材料。",
        merge_key="qualification-approval-letter",
    ),
    RuleDefinition(
        rule_id="QUAL-005",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"股权结构.*国有资本持股|国有资本持股\d+%"),
        rationale="将股权结构或国资持股比例作为准入条件，通常与具体履约能力无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除股权结构或国有资本持股比例要求，不得按企业组织形式设置门槛。",
        merge_key="qualification-ownership-structure",
    ),
    RuleDefinition(
        rule_id="QUAL-006",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"连续五个会计年度.*财务审计报告|由注册会计师事务所出具的财务审计报告"),
        rationale="要求连续多年审计报告，可能超出一般货物采购对供应商履约能力审查的必要范围。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-007"),
        source_section="申请人的资格要求",
        rewrite_hint="删除连续多年审计报告要求，如确需财务能力证明，应控制在与项目规模相匹配的必要范围。",
        merge_key="qualification-audit-history",
    ),
    RuleDefinition(
        rule_id="QUAL-007",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"国家级特色企业|国家级专精特新|专精特新"),
        rationale="将企业特色称号或政策认定结果作为准入门槛，通常与具体项目履约无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-010", "RULE-014"),
        related_reference_ids=("LEGAL-001", "CASESRC-001", "CASESRC-006"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业特色、专精特新等称号门槛，改为与项目直接相关的履约能力要求。",
        merge_key="qualification-award",
    ),
    RuleDefinition(
        rule_id="QUAL-008",
        issue_type="geographic_restriction",
        pattern=re.compile(r"本地分支机构|本地售后服务机构|本地服务团队|项目所在地设有.*办公场所|在项目所在地设有|常驻服务机构"),
        rationale="通过本地机构、常驻团队或办公场所要求限制供应商范围，可能构成属地性门槛。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除本地机构或办公场所前置要求，改为服务响应时效、到场时限等履约要求。",
        merge_key="qualification-geographic",
    ),
    RuleDefinition(
        rule_id="QUAL-009",
        issue_type="geographic_restriction",
        pattern=re.compile(r"本地注册|项目所在地注册|属地纳税|纳税地须为|在深圳市注册"),
        rationale="直接按注册地、纳税地或项目所在地要求限制供应商，可能构成差别待遇。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除注册地、纳税地等属地门槛，改为与履约直接相关的服务能力要求。",
        merge_key="qualification-geographic",
    ),
    RuleDefinition(
        rule_id="QUAL-010",
        issue_type="personnel_restriction",
        pattern=re.compile(r"年龄不超过\d+岁|年龄在\d+岁以下|限男性|限女性|男性优先|女性优先|身高\d+\s*cm|户籍"),
        rationale="对人员年龄、性别、身高或户籍作限定，通常与一般履约能力无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001",),
        source_section="申请人的资格要求",
        rewrite_hint="删除人员年龄、性别、身高、户籍等画像限制，改为岗位能力和履约经验要求。",
        merge_key="qualification-personnel-profile",
    ),
    RuleDefinition(
        rule_id="QUAL-011",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"具有.*类似项目业绩.*方可投标|近\d+年.*类似项目业绩.*不得少于\d+个|承接过.*项目业绩.*作为资格条件|提供类似业绩证明材料方可"),
        rationale="将类似业绩直接前置为资格条件，容易把履约经验要求泛化成准入门槛。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-012"),
        related_reference_ids=("LEGAL-001", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除类似业绩前置门槛，如确需评价履约经验，可在评分中低权重、与项目规模相匹配地设置。",
        merge_key="qualification-past-performance",
    ),
    RuleDefinition(
        rule_id="QUAL-012",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"年均纳税额.*不低于|近三年年均纳税额|连续\s*\d+\s*年以上经营业绩证明|单项合同金额不低于\s*\d+\s*万元"),
        rationale="将一般纳税额、经营年限或单项合同金额直接设置为资格门槛，通常超出法定资格和必要履约能力范围。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-012", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-002", "CASESRC-007"),
        source_section="申请人的资格要求",
        rewrite_hint="删除一般纳税额、经营年限和单项合同金额门槛，仅保留与项目规模直接相关、确有必要的履约能力要求。",
        merge_key="qualification-financial-threshold",
    ),
    RuleDefinition(
        rule_id="QUAL-014",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"员工总数不得少于\d+人|在册员工总数不得少于\d+人|参保人数不得少于\d+人|月均参保人数.*不少于\d+人|资产总额不低于\d+万元|平均资产总额不低于\d+万元"),
        rationale="将员工人数、参保人数或资产规模直接设置为资格门槛，通常超出法定准入和履约必需能力范围。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-007", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除员工人数、参保人数和资产规模门槛，仅保留与项目履约直接相关的法定资质和能力证明。",
        merge_key="qualification-financial-threshold",
    ),
    RuleDefinition(
        rule_id="QUAL-013",
        issue_type="qualification_domain_mismatch",
        pattern=re.compile(r"有害生物防制|SPCA登记证书|SPCA"),
        rationale="资格条件出现与采购标的领域明显不匹配的资质或登记要求，疑似模板错贴或条款域与标的域不一致。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001",),
        source_section="申请人的资格要求",
        rewrite_hint="删除与项目标的不相称的资质或登记要求，改为与供货、安装和售后履约直接相关的条件。",
        merge_key="qualification-domain-mismatch",
    ),
]
