from __future__ import annotations

import re

from agent_compliance.agents.compliance_review.rules.base import RuleDefinition


RULES = [
    RuleDefinition(
        rule_id="TECH-001",
        issue_type="narrow_technical_parameter",
        pattern=re.compile(r"无线插拔技术|无需防水盖|12MHz、20MHz|兼容高清电子胃肠镜"),
        rationale="技术路线或参数组合较细，存在指向少数产品体系的风险。",
        severity_score=2,
        related_rule_ids=("RULE-003",),
        related_reference_ids=("LEGAL-001", "CASESRC-001"),
        source_section="技术要求",
        rewrite_hint="改为功能效果导向的兼容性或性能要求，并补充必要性说明。",
        merge_key="technical-parameter-narrow",
    ),
    RuleDefinition(
        rule_id="TECH-002",
        issue_type="narrow_technical_parameter",
        pattern=re.compile(r"指定品牌|指定型号|专有平台|专有接口|仅兼容.*现有系统|兼容.*原有设备"),
        rationale="兼容性、平台或接口要求写法较窄，存在锁定既有品牌或技术体系的风险。",
        severity_score=2,
        related_rule_ids=("RULE-003",),
        related_reference_ids=("LEGAL-001", "CASESRC-001"),
        source_section="技术要求",
        rewrite_hint="将品牌、平台或既有系统要求改为功能兼容和效果要求，并补充必要性说明。",
        merge_key="technical-compatibility",
    ),
    RuleDefinition(
        rule_id="TECH-003",
        issue_type="technical_justification_needed",
        pattern=re.compile(r"202\d年.*投标截止日前.*(CMA|CNAS)|第三方.*(CMA|CNAS).*(阻燃|抗菌|抗病毒|防霉|盐雾|致癌染料|有机锡|邻苯|含氯苯酚)"),
        rationale="检测报告时段、机构资质与多项性能指标叠加设置，可能具有场景合理性，但通常需要采购人进一步说明必要性。",
        severity_score=2,
        related_rule_ids=("RULE-003", "RULE-016"),
        related_reference_ids=("LEGAL-001", "CASESRC-001"),
        source_section="技术要求",
        rewrite_hint="补充市场调研、场景必要性和检测要求设置依据，能以国家或行业标准表述的尽量不叠加细化证明形式。",
        merge_key="technical-justification",
    ),
    RuleDefinition(
        rule_id="TECH-004",
        issue_type="technical_justification_needed",
        pattern=re.compile(r"阻燃|抗菌|抗病毒|防霉|环保|盐雾|致癌染料|有机锡|邻苯|含氯苯酚"),
        rationale="技术指标涉及安全、环保或院感控制等场景要求时，可能合理，但需要结合采购场景和市场供给说明必要性。",
        severity_score=2,
        related_rule_ids=("RULE-003", "RULE-016"),
        related_reference_ids=("LEGAL-001", "CASESRC-001"),
        source_section="技术要求",
        rewrite_hint="如确需保留安全、环保或院感控制指标，应补充适用场景、标准依据和市场调研说明。",
        merge_key="technical-justification",
    ),
    RuleDefinition(
        rule_id="TECH-005",
        issue_type="technical_justification_needed",
        pattern=re.compile(r"生产日期必须是\s*202\d\s*年|生产日期必须为\s*202\d\s*年"),
        rationale="将核心设备生产日期直接限定为固定自然年度，形式上较窄，通常需要采购人补充必要性和市场可获得性说明。",
        severity_score=2,
        related_rule_ids=("RULE-003", "RULE-016"),
        related_reference_ids=("LEGAL-001",),
        source_section="技术要求",
        rewrite_hint="改为全新、未使用且符合交付要求的设备表述，或说明限定年度的必要性。",
        merge_key="technical-fixed-year",
    ),
    RuleDefinition(
        rule_id="TECH-006",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"必须为.*制造商.*专业工程师|专业工程师.*\d+\s*年以上工作经验"),
        rationale="对现场技术人员来源和年限要求限定过细，容易把制造商体系优势固化为准入或评分优势。",
        severity_score=2,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001",),
        source_section="技术要求",
        rewrite_hint="改为具备相应专业背景和安装调试经验，不宜限定人员必须来自制造商厂。",
        merge_key="technical-personnel-source",
    ),
]
