from __future__ import annotations

import re

from agent_compliance.rules.base import RuleDefinition


RULES = [
    RuleDefinition(
        rule_id="QUAL-001",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"外商投资及民营企业|国资企业不具备投标资格"),
        rationale="按企业性质限制供应商范围，可能构成差别待遇。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业性质限制，改回法定主体资格和履约必需能力要求。",
        merge_key="qualification-entity-type",
    ),
    RuleDefinition(
        rule_id="QUAL-002",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"注册资本不低于|年收入不低于|净利润不低于|经营年限不低于|年平均盈利不低于"),
        rationale="设置与项目履约弱相关的一般性财务或经营年限门槛。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-007", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除一般性财务和经营年限门槛，改用法定资质和履约能力证明。",
        merge_key="qualification-financial-threshold",
    ),
    RuleDefinition(
        rule_id="QUAL-003",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"国家级高新技术企业|AAA"),
        rationale="将企业称号、荣誉或信用等级作为门槛或高权重因素，可能与履约无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-010", "RULE-014"),
        related_reference_ids=("LEGAL-001", "CASESRC-001", "CASESRC-006"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业称号或荣誉门槛，改为与标的直接相关的履约能力条件。",
        merge_key="qualification-award",
    ),
    RuleDefinition(
        rule_id="QUAL-004",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"上级主管单位.*同意其参与投标的函件"),
        rationale="以主管单位同意函作为参与前提，通常与一般货物采购履约能力无直接对应关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-002"),
        source_section="申请人的资格要求",
        rewrite_hint="删除主管单位同意函要求，仅保留法定主体资格和履约所必需的证明材料。",
        merge_key="qualification-approval-letter",
    ),
    RuleDefinition(
        rule_id="QUAL-005",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"股权结构.*国有资本持股|国有资本持股\d+%"),
        rationale="将股权结构或国资持股比例作为准入条件，通常与具体履约能力无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-003"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="申请人的资格要求",
        rewrite_hint="删除股权结构或国有资本持股比例要求，不得按企业组织形式设置门槛。",
        merge_key="qualification-ownership-structure",
    ),
    RuleDefinition(
        rule_id="QUAL-006",
        issue_type="excessive_supplier_qualification",
        pattern=re.compile(r"连续五个会计年度.*财务审计报告|由注册会计师事务所出具的财务审计报告"),
        rationale="要求连续多年审计报告，可能超出一般货物采购对供应商履约能力审查的必要范围。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-015"),
        related_reference_ids=("LEGAL-001", "CASESRC-007"),
        source_section="申请人的资格要求",
        rewrite_hint="删除连续多年审计报告要求，如确需财务能力证明，应控制在与项目规模相匹配的必要范围。",
        merge_key="qualification-audit-history",
    ),
    RuleDefinition(
        rule_id="QUAL-007",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"国家级特色企业|国家级专精特新|专精特新"),
        rationale="将企业特色称号或政策认定结果作为准入门槛，通常与具体项目履约无直接关系。",
        severity_score=3,
        related_rule_ids=("RULE-003", "RULE-010", "RULE-014"),
        related_reference_ids=("LEGAL-001", "CASESRC-001", "CASESRC-006"),
        source_section="申请人的资格要求",
        rewrite_hint="删除企业特色、专精特新等称号门槛，改为与项目直接相关的履约能力要求。",
        merge_key="qualification-award",
    ),
]
