from __future__ import annotations

import re

from agent_compliance.rules.base import RuleDefinition


RULES = [
    RuleDefinition(
        rule_id="SCORE-001",
        issue_type="duplicative_scoring_advantage",
        pattern=re.compile(r"营业执照或事业单位法人证书等证明资料扫描件，可得\d+分"),
        rationale="资格证明材料不宜再次转化为评分优势。",
        severity_score=3,
        related_rule_ids=("RULE-004", "RULE-012"),
        related_reference_ids=("CASESRC-004",),
        source_section="评标信息",
        rewrite_hint="删除资格证明材料加分，避免将资格审查内容重复转化为评分优势。",
        merge_key="scoring-qualification-repeat",
    ),
    RuleDefinition(
        rule_id="SCORE-002",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"全国科技型中小企业证明|守合同重信用企业|奖项|荣誉|信用等级|驰名商标|著名商标|名牌产品|品牌价值|五星售后|商品售后服务评价"),
        rationale="与履约无明显关系的荣誉或企业属性不宜作为高分项。",
        severity_score=2,
        related_rule_ids=("RULE-010", "RULE-014", "RULE-004"),
        related_reference_ids=("CASESRC-001", "CASESRC-006"),
        source_section="评标信息",
        rewrite_hint="删除与履约无直接关系的荣誉、称号和信用等级加分项。",
        merge_key="scoring-award",
    ),
    RuleDefinition(
        rule_id="SCORE-003",
        issue_type="ambiguous_requirement",
        pattern=re.compile(r"方案极合理|条理极清晰|综合比较|优、良、中、差|评审为优|评审为良|评审为中|评审为差"),
        rationale="主观评分分档表述较多，缺少量化锚点。",
        severity_score=2,
        related_rule_ids=("RULE-004", "RULE-011"),
        related_reference_ids=("CASESRC-003",),
        source_section="评标信息",
        rewrite_hint="把主观描述拆成分项分档和可核验指标，减少自由裁量空间。",
        merge_key="scoring-subjective-band",
    ),
    RuleDefinition(
        rule_id="SCORE-004",
        issue_type="excessive_scoring_weight",
        pattern=re.compile(r"质量管理体系认证.*得\s*\d+\s*分|职业健康安全管理体系认证.*得\s*\d+\s*分|环境管理体系认证.*得\s*\d+\s*分"),
        rationale="将体系认证设置为高权重评分项，可能过度放大与项目履约不完全对应的管理性证明。",
        severity_score=2,
        related_rule_ids=("RULE-004", "RULE-010"),
        related_reference_ids=("CASESRC-001", "CASESRC-006"),
        source_section="评标信息",
        rewrite_hint="降低体系认证类评分权重，避免将管理性认证作为决定性高分项。",
        merge_key="scoring-certification-weight",
    ),
    RuleDefinition(
        rule_id="SCORE-005",
        issue_type="post_award_proof_substitution",
        pattern=re.compile(r"中标（成交）\s*后\s*\d+\s*个月内取得评审因素相关认证证书|中标后\s*\d+\s*个月内取得"),
        rationale="允许中标后补交或补取得评审证明，会削弱投标时点评分依据的真实性和可比性。",
        severity_score=2,
        related_rule_ids=("RULE-004", "RULE-010"),
        related_reference_ids=("CASESRC-003", "CASESRC-006"),
        source_section="评标信息",
        rewrite_hint="取消中标后补证安排，评分应以投标截止时已经取得的有效证明为准。",
        merge_key="scoring-post-award-proof",
    ),
    RuleDefinition(
        rule_id="SCORE-006",
        issue_type="excessive_scoring_weight",
        pattern=re.compile(r"每提供\s*1\s*个得\s*20\s*分.*最高得\s*100\s*分|最高得\s*100\s*分"),
        rationale="将单一业绩或认证因素设置为过高分值，可能使评分结构失衡并过度偏向既有供应商。",
        severity_score=2,
        related_rule_ids=("RULE-004", "RULE-012"),
        related_reference_ids=("CASESRC-002", "CASESRC-003"),
        source_section="评标信息",
        rewrite_hint="降低单类因素分值上限，并将高分项拆散到与履约直接相关的多个可验证指标中。",
        merge_key="scoring-weight-balance",
    ),
    RuleDefinition(
        rule_id="SCORE-007",
        issue_type="excessive_scoring_weight",
        pattern=re.compile(r"评审为优加\s*80\s*分|评审为良加\s*50\s*分|评审为中加\s*20\s*分"),
        rationale="样品主观评价分值过高，可能使样品感观判断对总分产生过强影响。",
        severity_score=2,
        related_rule_ids=("RULE-004", "RULE-011"),
        related_reference_ids=("CASESRC-003",),
        source_section="评标信息",
        rewrite_hint="降低样品主观评价分值，并改为按具体缺陷、尺寸、材质、工艺等可核验指标评分。",
        merge_key="scoring-sample-weight",
    ),
    RuleDefinition(
        rule_id="SCORE-008",
        issue_type="geographic_restriction",
        pattern=re.compile(r"本地项目业绩.*得\d+分|省内、本地存在相关项目的业绩|在项目所在地设有服务机构.*得\d+分|本地服务团队.*得\d+分|驻点服务机构.*得\d+分|本地售后网点.*得\d+分|本地备件库.*得\d+分"),
        rationale="在评分项中对本地业绩、本地服务机构或本地团队给予加分，可能形成变相属地倾斜。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-004"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="评标信息",
        rewrite_hint="删除本地业绩、本地服务机构或本地团队加分，改为统一的响应时效、服务方案和履约能力评价。",
        merge_key="scoring-geographic",
    ),
    RuleDefinition(
        rule_id="SCORE-009",
        issue_type="scoring_content_mismatch",
        pattern=re.compile(r"安装的工程案例|工程案例；|具有CMA标识的第三方检测报告"),
        rationale="方案或计划评分中混入工程案例、检测报告形式等内容，容易把与方案本体不同层次的材料转化为评分优势。",
        severity_score=3,
        related_rule_ids=("RULE-004", "RULE-011", "RULE-012"),
        related_reference_ids=("CASESRC-003",),
        source_section="评标信息",
        rewrite_hint="将工程案例和检测报告形式要求移出方案评分项，方案评分仅围绕实施内容本身进行量化评价。",
        merge_key="scoring-content-mismatch",
    ),
    RuleDefinition(
        rule_id="SCORE-010",
        issue_type="geographic_restriction",
        pattern=re.compile(r"1小时(?:（60分钟）)?内?.*到达现场.*得(?:100|满)分|1\.5小时(?:（90分钟）)?内?.*到达现场.*得(?:50|半)分|1小时内到达现场处理问题|60分钟内到达现场.*得分|2小时内到达现场.*得分|4小时内到达现场.*得分|12小时内提供备品备件.*得分|驻场服务.*得分"),
        rationale="对极短到场时限给予高分，容易对本地驻点或既有服务网络形成事实上的属地倾斜。",
        severity_score=3,
        related_rule_ids=("RULE-002", "RULE-004"),
        related_reference_ids=("LEGAL-001", "CASESRC-005"),
        source_section="评标信息",
        rewrite_hint="删除极短到场时限的高分设置，改为售后响应机制、备件保障和故障处置能力评价。",
        merge_key="scoring-geographic",
    ),
    RuleDefinition(
        rule_id="SCORE-011",
        issue_type="scoring_content_mismatch",
        pattern=re.compile(r"从业人员超过\d+人|资产总额达到\d+万元以上|成立时间满\d+年"),
        rationale="评分项将企业规模、资产或成立年限直接转化为竞争优势，通常与具体履约质量无直接对应关系。",
        severity_score=3,
        related_rule_ids=("RULE-004", "RULE-012"),
        related_reference_ids=("LEGAL-001", "CASESRC-002"),
        source_section="评标信息",
        rewrite_hint="删除按企业规模、资产和成立年限打分的内容，仅保留与项目履约直接相关的评分因素。",
        merge_key="scoring-content-mismatch",
    ),
    RuleDefinition(
        rule_id="SCORE-012",
        issue_type="scoring_content_mismatch",
        pattern=re.compile(r"有机产品认证证书|水运机电工程专项监理企业资质认定|采用国际标准产品确认证书|采用国际标准产品标志证书|生活垃圾分类服务能力认证|商品售后服务评价体系认证|售后服务认证证书"),
        rationale="评分项中出现与当前采购标的关联不足或领域明显错位的证书、资质或认证，疑似模板错贴或内容错位。",
        severity_score=3,
        related_rule_ids=("RULE-004", "RULE-010", "RULE-014"),
        related_reference_ids=("LEGAL-001",),
        source_section="评标信息",
        rewrite_hint="删除与采购标的不相称的认证和资质评分内容，仅保留与发电机组供货安装直接相关的辅助性证明。",
        merge_key="scoring-domain-mismatch",
    ),
    RuleDefinition(
        rule_id="SCORE-013",
        issue_type="irrelevant_certification_or_award",
        pattern=re.compile(r"中国驰名商标|广东省著名商标|国家级质量奖|品牌价值评价|五星级售后服务认证"),
        rationale="将品牌荣誉、质量奖或售后星级认证作为高分项，可能把与履约关联有限的品牌形象因素转化为竞争优势。",
        severity_score=2,
        related_rule_ids=("RULE-010", "RULE-014", "RULE-004"),
        related_reference_ids=("CASESRC-001", "CASESRC-006"),
        source_section="评标信息",
        rewrite_hint="删除品牌荣誉、质量奖和售后星级认证加分，改为与项目履约直接相关的客观服务能力指标。",
        merge_key="scoring-award",
    ),
]
