from __future__ import annotations

from agent_compliance.core.pipelines.requirement_scope_layer import (
    EFFECT_REFERENCE_ONLY,
    EFFECT_STRONG_BINDING,
    EFFECT_WEAK_BINDING,
    FUNCTION_ACCEPTANCE_PROCEDURE,
    FUNCTION_COMMERCIAL_TERM,
    FUNCTION_IMPLEMENTATION_OBLIGATION,
    FUNCTION_INTEGRATION_OBLIGATION,
    FUNCTION_PROOF_REQUIREMENT,
    FUNCTION_QUALIFICATION_GATE,
    FUNCTION_REFERENCE_NOTE,
    FUNCTION_SCORING_EVIDENCE,
    FUNCTION_SCORING_FACTOR,
    FUNCTION_TECHNICAL_PARAMETER,
    FUNCTION_TEMPLATE_RESIDUE_CANDIDATE,
    RequirementScopeClassification,
    SCOPE_ACCEPTANCE_REQUIREMENT,
    SCOPE_ATTACHMENT_SAMPLE,
    SCOPE_BACKGROUND_TEXT,
    SCOPE_COMMERCIAL_REQUIREMENT,
    SCOPE_FORMAT_TEXT,
    SCOPE_PROMPT_TEXT,
    SCOPE_REQUIREMENT_BODY,
    SCOPE_SCORING_RULE,
    SCOPE_TECHNICAL_REQUIREMENT,
    SCOPE_TEMPLATE_TEXT,
    annotate_document_requirement_scope,
    apply_clause_scope_annotation,
    classify_clause_scope,
    classify_finding_scope,
    classify_requirement_scope,
    filter_effective_requirement_clauses,
    filter_effective_requirement_findings,
    filter_high_weight_requirement_clauses,
    filter_substantive_requirement_clauses,
    filter_substantive_requirement_findings,
    is_effective_requirement_clause,
    is_effective_requirement_finding,
    is_high_weight_requirement_clause,
    is_high_weight_requirement_finding,
    is_substantive_requirement_clause,
    is_substantive_requirement_finding,
)


REQUIREMENT_SCOPE_BODY = "body"
REQUIREMENT_SCOPE_TEMPLATE = "template"
REQUIREMENT_SCOPE_HINT = "hint"
REQUIREMENT_SCOPE_FORMAT = "format"

__all__ = [
    "RequirementScopeClassification",
    "REQUIREMENT_SCOPE_BODY",
    "REQUIREMENT_SCOPE_TEMPLATE",
    "REQUIREMENT_SCOPE_HINT",
    "REQUIREMENT_SCOPE_FORMAT",
    "SCOPE_REQUIREMENT_BODY",
    "SCOPE_SCORING_RULE",
    "SCOPE_TECHNICAL_REQUIREMENT",
    "SCOPE_COMMERCIAL_REQUIREMENT",
    "SCOPE_ACCEPTANCE_REQUIREMENT",
    "SCOPE_TEMPLATE_TEXT",
    "SCOPE_PROMPT_TEXT",
    "SCOPE_FORMAT_TEXT",
    "SCOPE_BACKGROUND_TEXT",
    "SCOPE_ATTACHMENT_SAMPLE",
    "FUNCTION_QUALIFICATION_GATE",
    "FUNCTION_SCORING_FACTOR",
    "FUNCTION_SCORING_EVIDENCE",
    "FUNCTION_TECHNICAL_PARAMETER",
    "FUNCTION_PROOF_REQUIREMENT",
    "FUNCTION_IMPLEMENTATION_OBLIGATION",
    "FUNCTION_INTEGRATION_OBLIGATION",
    "FUNCTION_COMMERCIAL_TERM",
    "FUNCTION_ACCEPTANCE_PROCEDURE",
    "FUNCTION_REFERENCE_NOTE",
    "FUNCTION_TEMPLATE_RESIDUE_CANDIDATE",
    "EFFECT_STRONG_BINDING",
    "EFFECT_WEAK_BINDING",
    "EFFECT_REFERENCE_ONLY",
    "annotate_document_requirement_scope",
    "apply_clause_scope_annotation",
    "classify_requirement_scope",
    "classify_clause_scope",
    "classify_finding_scope",
    "is_effective_requirement_clause",
    "is_high_weight_requirement_clause",
    "is_effective_requirement_finding",
    "is_high_weight_requirement_finding",
    "filter_effective_requirement_clauses",
    "filter_high_weight_requirement_clauses",
    "filter_effective_requirement_findings",
    "filter_substantive_requirement_clauses",
    "filter_substantive_requirement_findings",
    "is_substantive_requirement_clause",
    "is_substantive_requirement_finding",
]
